### ISSUE TITLE
requirement of PHP 8.2

### ISSUE THREAD

**Issue by kamekun** [sokeio/laravel-grapesjs-builder-community#4]
Hello, it doesn't make much sense that this tool requires PHP 8.2.x when the lasted version Laravel 10 required a PHP version 8.1.x should be inline with the core framework of Laravel.

Digging a little bit the only change to be compatible with PHP 8.1 its the const on the trial you have, those const require by PHP 8.2 just that, so make sense to roll back those changes and make it compatible with  <= 8.1 instead  >=8.2

Another topic with the lasted changes of name to sokeio the package.json is not working as its referering to old byteplatform. Default installation its not working. Trying a lot of stuff to make it work.

Regards,-

**Comment by devhau** [comment]
Hello,
really sorry about that.
I am changing the core to be more compatible with many applications.
This section is not yet available for sokeio. In a few weeks I will update it again to make it more functional and compatible with sokeio.
Changing byteplatform to sokeio changes it so it can be more compact.
you join facebook group : https://www.facebook.com/groups/byteplatform
Thank you love!

**Comment by kamekun** [comment]
Its possible to get lasted old working source code version? wanted to test it / modify it a little bit. But even the demo page [](https://pagebuilder.asia/admin/auth/login) its not working right now.

**Comment by devhau** [comment]
hello,
you change package:
 "byteplatform/byteplatform": "^1.0.3"=> "sokeio/framework":"dev-main",
 "byteplatform/builder": "^1.0.3"=> "sokeio/grapesjs-builder":"dev-main",
 and add package : "sokeio/admin":"dev-main",
 
You follow it:
 
https://github.com/sokeio/framework
https://github.com/sokeio/admin
https://github.com/sokeio/grapesjs-builder
https://github.com/sokeio/seo

**Comment by kamekun** [comment]
Found this problem with the changes of packages:
Loading composer repositories with package information Updating dependencies Your requirements could not be resolved to an installable set of packages.
```
  Problem 1
    - Root composer.json requires sokeio/grapesjs-builder dev-main -> satisfiable by sokeio/grapesjs-builder[dev-main].
    - sokeio/grapesjs-builder dev-main requires sokeio/seo dev-main -> found sokeio/seo[dev-main] but it does not match your minimum-stability.
```

**Comment by devhau** [comment]
hello,
i fixed it.
you remove .env and reinstall
note: SOKEIO_SETUP=true in .env.example or .env
step1:
<img width="661" alt="image" src="https://github.com/sokeio/laravel-grapesjs-builder-community/assets/50167033/cad1324a-5945-472d-b490-aa8ef5d59b8e">
step2:
<img width="661" alt="image" src="https://github.com/sokeio/laravel-grapesjs-builder-community/assets/50167033/c83d7b66-4102-492c-8ff5-bef22fda9bf5">
step3:
<img width="661" alt="image" src="https://github.com/sokeio/laravel-grapesjs-builder-community/assets/50167033/0bac1085-3c27-4b55-9c00-b60c3909f175">
step4:
<img width="661" alt="image" src="https://github.com/sokeio/laravel-grapesjs-builder-community/assets/50167033/6888a031-858b-4e17-98ed-2d7f1826f1a9">
<img width="661" alt="image" src="https://github.com/sokeio/laravel-grapesjs-builder-community/assets/50167033/89963680-9206-4f57-ac22-979a03b7b61b">

let'go click Finsh step.

**Comment by kamekun** [comment]
Still failing, can you try to make an tag release  for this repo with these changes?
```
> @php artisan package:discover --ansi
In AppServiceProvider.php line 26:
  Class "BytePlatform\Facades\Shortcode" not found
In AppServiceProvider.php line 26:
  Class "BytePlatform\Facades\Shortcode" not found

```

**Comment by devhau** [comment]
thanks kamekun!

https://github.com/sokeio/laravel-grapesjs-builder-community/releases/tag/v1.0.1
this error is design . you remove folder public/platform . recopy folder platform from vender.
